name: Run Changed Sources in Pull Requests

# Only run on pushes
on:
  pull_request:
    paths:
      - 'sources/**/*.json'
      - '.github/workflows/run_changed_sources.yml'

jobs:
  run-source:
    runs-on: ubuntu-22.04
    permissions:
      # These are important to get the batch-machine image
      contents: read
      packages: write
    container:
      image: ghcr.io/openaddresses/batch-machine:latest
      credentials:
        username: "$"
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run machine
        run: |
          mkdir output
          python3 ci/run_changed_sources.py
      - name: Archive extracted data
        uses: actions/upload-artifact@v3
        with:
          name: output
          path: |
            output
      - name: Upload to R2
        uses: shallwefootball/s3-upload-action@v1.3.3
        id: R2
        with:
          aws_key_id: ${{ secrets.R2_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.R2_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.R2_BUCKET }}
          endpoint: ${{ secrets.R2_ENDPOINT }}
          destination_dir: "runs/gh-${{ github.run_id }}"
          source_dir: 'output'
      - name: Get R2 output
        run: |
          echo "R2 destination: ${{steps.R2.outputs.object_key}}"
      - name: Add Comment
        uses: peter-evans/create-or-update-comment@v2
        env:
          PR_NUMBER: ${{ github.event.number }}
        with:
          issue-number: ${{ env.PR_NUMBER }}
          body: |-
            Comment!
