name: Run Changed Sources in Pull Requests

# Only run on pushes
on:
  pull_request:
    paths:
      - 'sources/**/*.json'
      - '.github/workflows/*.yml'

jobs:
  run-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install gdal
        run: |
          sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install gdal-bin libgdal-dev
      - name: Install tippecanoe
        run: |
          curl -sL https://github.com/felt/tippecanoe/archive/refs/tags/2.29.0.tar.gz | tar -xz
          cd tippecanoe-2.29.0
          make -j
          sudo make install
          cd ..
      - name: Install machine
        run: |
          curl -sL https://github.com/openaddresses/batch-machine/archive/refs/tags/8.1.1.tar.gz | tar -xz
          pip --quiet install ./batch-machine-8.1.1
      - name: Run machine
        run: |
          mkdir output
          openaddr-process-one sources/us/mn/aitkin.json
