name: Run Changed Sources in Pull Requests

# Only run on pushes
on:
  pull_request:
    paths:
      - 'sources/**/*.json'
      - '.github/workflows/*.yml'

jobs:
  run-source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install tippecanoe
        run: |
          git clone https://github.com/felt/tippecanoe.git
          cd tippecanoe
          git checkout 2.29.0
          make -j
          sudo make install
      - name: Install machine
        run: |
          pip --quiet install .
