name: Run Changed Sources in Pull Requests

# Only run on pushes
on:
  pull_request:
    paths:
      - 'sources/**/*.json'
      - '.github/workflows/*.yml'

jobs:
  run-source:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install gdal
        run: |
          sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
          sudo apt-get update
          sudo apt-get install gdal-bin=3.6.4+dfsg-1~jammy0 libgdal-dev=3.6.4+dfsg-1~jammy0
          pip --quiet install gdal==3.6.4
      - name: Install tippecanoe
        run: |
          curl -sL https://github.com/felt/tippecanoe/archive/refs/tags/2.29.0.tar.gz | tar -xz
          cd tippecanoe-2.29.0
          make -j
          sudo make install
          cd ..
      - name: Install cairo
        run: |
          sudo apt-get install libcairo2-dev
          pip --quiet install cairocffi
      - name: Install machine
        run: |
          curl -sL https://github.com/openaddresses/batch-machine/archive/refs/tags/8.1.1.tar.gz | tar -xz
          pip --quiet install ./batch-machine-8.1.1
      - name: Run machine
        run: |
          mkdir output
          openaddr-process-one -ln addresses \
                               -ls county \
                               --render-preview \
                               --mapbox-key="pk.eyJ1IjoiaWFuZGVlcyIsImEiOiJjbGxpcGhwMTkxanVkM2xtbHphNnN0cHA0In0.vI2-u4up38ddKVadUljnYw" \
                               sources/us/mn/aitkin.json \
                               output
